name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

env: 
  REACT_APP_API_KEY: ${{secrets.IDKEY}}
  REACT_APP_AUTH_DOMAIN: ${{secrets.DOMAIN}}
  REACT_APP_PROJECT_ID:  ${{secrets.ID}}
  REACT_APP_STORAGE_BUCKET: ${{secrets.BUCKET}}
  REACT_APP_MESSAGING_SENDER_ID: ${{secrets.SENDER_ID}}
  REACT_APP_APP_ID: ${{secrets.APP_ID}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
